source 'https://rubygems.org'

gem 'rails', '4.2.3', require: false
gem 'rails-api',      require: false
gem 'pg',             require: false
gem 'oj',             require: false
gem 'oj_mimic_json'
gem 'puma',           require: false

group :development do
  gem 'pry'
  gem 'pry-rails'
end
